# Generated by Django 3.2.15 on 2022-08-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='회사이름')),
                ('country', models.CharField(max_length=20, verbose_name='국가')),
                ('region', models.CharField(max_length=20, verbose_name='지역')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=20, verbose_name='채용포지션')),
                ('compensation', models.IntegerField(default=0, verbose_name='채용 보상금')),
                ('skill', models.CharField(max_length=20, verbose_name='사용 기술')),
                ('content', models.TextField(max_length=200, verbose_name='채용내용')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posting.company')),
            ],
        ),
    ]
