# Generated by Django 3.2.13 on 2022-08-24 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_auto_20220822_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.company'),
        ),
    ]
