# Generated by Django 3.2.13 on 2022-08-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_alter_jobposting_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_posting.user', unique=True)),
            ],
        ),
    ]
