# Generated by Django 3.2.13 on 2022-08-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_applyjobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_posting.user'),
        ),
    ]
